Added Update REPO Function

diff --git a/spm/spm b/spm/spm
--- a/spm/spm
+++ b/spm/spm
@@ -9,7 +9,7 @@
 # Created by AwlsomeAlex [GPLv3]
 # Compatible with StarOS & Star Library
 
-SPM_VER="GIT"
+SPM_VER="GIT-20180209-001"
 echo "The Star Package Manager Library will now be loaded. If not found the program will exit."
 
 # Check if Native or Hosted and load SPM Library
@@ -26,5 +26,5 @@ fi
 if [[ ! $SPML_VER == $SPM_VER ]]; then
 	echo "WARNING: The Executable '$SPM_VER' is a different version than the Library '$SPML_VER'. Proceed with caution!"
 fi
-#update_repo || echo "An internet connection could not be established. This is required."
+update_repo || echo "An internet connection could not be established. This is required."
 
