Bug Fixes

diff --git a/spm/spm b/spm/spm
--- a/spm/spm
+++ b/spm/spm
@@ -10,19 +10,21 @@
 # Compatible with StarOS & Star Library
 
 SPM_VER="GIT"
+echo "The Star Package Manager Library will now be loaded. If not found the program will exit."
 
 # Check if Native or Hosted and load SPM Library
 if [ -f /etc/staros.txt ]; then
-	echo "This is running on StarOS."
 	NATIVE=True
-	source /lib/spm.lib || echo "WARNING: The Star Package Manager Libray could not be found. This is a problem." && exit 1
+	source /lib/spm.lib || exit 1
+	assurance
 else
-	echo "Running on another Linux Distribution."
 	NATIVE=False
-	source spm.lib || echo "WARNING: The Star Package Manager Library could not be found. Please place it in the same directory as the executable." && exit 1
+	. spm.lib || exit 1
+	assurance
 fi
-if ! [[ $SPML_VER == $SPM_VER ]]; then
-	echo "WARNING: The Executable $SPM_VER is a different version than the Library $SPML_VER. Proceed with caution!"
+
+if [[ ! $SPML_VER == $SPM_VER ]]; then
+	echo "WARNING: The Executable '$SPM_VER' is a different version than the Library '$SPML_VER'. Proceed with caution!"
 fi
-update_repo || echo "An internet connection could not be established. This is required."
+#update_repo || echo "An internet connection could not be established. This is required."
 
